### ISSUE TITLE
[BUG] `remove-to-emp-rules` makes `convert-to-cnf` output include eliminated nts

### ISSUE THREAD

**Issue by jasonhemann** [morazanm/fsm#21]
In some cases `convert-to-cnf` produces incorrect cfgs. The immediate culprit is `remove-to-emp-rules`. Even as we remove epsilon from the RHSs of some rules, this function also keeps the old versions of the rules that contain the epsilon-generating non-terminal on the RHS. This leads to the failing grammar in the example below.

More broadly, it surprises me that epsilon removal is a one-pass map operation. I had expected multiple passes for when to-epsilon removal begets more to-epsilon removal, e.g. `((A -> BB) (B -> CC) (C -> ε))`.

Note here that, although X is eliminated from the nonterminals, it remains on the RHSs of some rules.
```
cfg.rkt> (convert-to-cnf 
          (make-cfg '(X Y Z)
                    '(a b c)
                    (list '(X -> ε)
                          '(Y -> XXZ)
                          '(Z -> abc))
                    'Y))
(cfg
 '(A B C Z Y)
 '(a b c)
 (list
  (cfg-rule 'A '(a))
  (cfg-rule 'B '(b))
  (cfg-rule 'C '(c))
  (cfg-rule 'Y '(X Y))
  (cfg-rule 'Y '(X Z))
  (cfg-rule 'Z '(A Z))
  (cfg-rule 'Z '(B C))
  (cfg-rule 'Y '(A Z))
  (cfg-rule 'Y '(B C)))
 'Y)
```

**Comment by morazanm** [comment]
convert-to-cnf is fixed in cfg.rkt. It now properly converts a cfg to Chomsky Normal Form. FOr example, the grammar used in the bug report:

(define G (make-cfg '(X Y Z A)
                      '(a b c e)
                      (list '(X -> ε)
                            '(Y -> XXZ)
                            '(Y -> XX)
                            '(Z -> abc)
                            '(A -> e))
                      'Y))

converts to: 

(cfg
 '(Y-3969019 A-3969020 B C T-3969022 Y-3969019)
 '(a b c e)
 (list
  (cfg-rule 'Y-3969019 '(ε))
  (cfg-rule 'A-3969020 '(a))
  (cfg-rule 'B '(b))
  (cfg-rule 'C '(c))
  (cfg-rule 'T-3969022 '(B C))
  (cfg-rule 'Y-3969019 '(A-3969020 T-3969022)))
 'Y-3969019)
