### ISSUE TITLE
bug: Mac Cannot Find .dot File to Generate .png File

### ISSUE THREAD

**Issue by oliwial23** [morazanm/fsm#60]
## Describe the bug
The iOS operating system cannot seem to find the .dot file to generate the .png file, after running sm-visualize.

## Steps to Reproduce
1) Run the following code:
```racket
#lang fsm
(define EVEN-A-ODD-B (make-dfa '(S M N P)
                               '(a b)
                               'S
                               '(N)
                               '((S a P)
                                 (S b N)
                                 (M a N)
                                 (M b P)
                                 (N a M)
                                 (N b S)
                                 (P a S)
                                 (P b M))
                               'no-dead))
(sm-visualize EVEN-A-ODD-B)
```
2) Click on black "DGR" button.

## Expected Behavior
A .png file should be generated, showing a graph. 

## OS Observed On
macOS Ventura 13.1

## Screenshots
<img width="1440" alt="Bildschirm­foto 2023-02-15 um 13 34 40" src="https://user-images.githubusercontent.com/119520637/219121435-5bb97de2-58fd-43a4-9c11-6a4bfe3b4e4d.png">

**Comment by jschappel** [comment]
@oliwial23 Hello :wave: . It seems that that the `dot` command is not on your computers path. Would you mind running the following commands in your terminal for me and posting the results?
1) `whereis dot`
2) If you installed graphviz using `homebrew` run `brew list | grep graphviz -i`. If you isntalled graphviz using `macports` run `port installed`

**Comment by jschappel** [comment]
@oliwial23 would you mind re-installing fsm and trying again? We pushed a potential fix

**Comment by oliwial23** [comment]
Hello @jschappel, I'm afraid the re-installing did not work. 
Here are the three commands you asked for:

1. whereis dot
Oliwia@kempinskis-mbp ~ % whereis dot
dot: /usr/local/bin/dot /usr/local/share/man/man1/dot.1

2. brew list | grep graphviz -i
Oliwia@kempinskis-mbp ~ % brew list | grep graphviz -i
graphviz

3. port installed
Oliwia@kempinskis-mbp ~ % port installed
The following ports are currently installed:
  aom @3.5.0_0 (active)
  autoconf @2.71_1 (active)
  autoconf-archive @2022.09.03_0 (active)
  automake @1.16.5_0 (active)
  brotli @1.0.9_2 (active)
  bzip2 @1.0.8_0 (active)
  cairo @1.17.6_0+quartz+x11 (active)
  dav1d @1.0.0_0 (active)
  db48 @4.8.30_4 (active)
  expat @2.5.0_0 (active)
  fontconfig @2.14.2_0 (active)
  freetype @2.12.1_0 (active)
  fribidi @1.0.12_0 (active)
  gd2 @2.3.3_2+x11 (active)
  gdbm @1.23_0 (active)
  gdk-pixbuf2 @2.42.9_2 (active)
  gettext @0.21_0 (active)
  gettext-runtime @0.21_0 (active)
  gettext-tools-libs @0.21_0 (active)
  giflib @4.2.3_0 (active)
  glib2 @2.70.5_0+x11 (active)
  gobject-introspection @1.72.0_0 (active)
  graphite2 @1.3.13_1 (active)
  graphviz @7.1.0_0+pangocairo+x11 (active)
  gts @0.7.6-20121130_1 (active)
  harfbuzz @6.0.0_0 (active)
  icu @72.1_0 (active)
  lerc @4.0.0_1 (active)
  libde265 @1.0.11_0 (active)
  libedit @20221030-3.1_0 (active)
  libffi @3.4.4_0 (active)
  libheif @1.14.2_0 (active)
  libiconv @1.17_0 (active)
  libjpeg-turbo @2.1.5_0 (active)
  libLASi @1.1.3_1 (active)
  libnetpbm @11.01.00_0 (active)
  libpixman @0.38.4_0 (active)
  libpng @1.6.39_0 (active)
  libtextstyle @0.21_0 (active)
  libtool @2.4.7_0 (active)
  libxml2 @2.10.3_1 (active)
  lz4 @1.9.4_0 (active)
  m4 @1.4.19_1 (active)
  ncurses @6.4_0 (active)
  openssl @3_9 (active)
  openssl3 @3.0.8_1+legacy (active)
  ossp-uuid @1.6.2_13+perl5_34 (active)
  pango @1.50.7_0+quartz+x11 (active)
  pcre @8.45_0 (active)
  perl5.34 @5.34.1_0 (active)
  pkgconfig @0.29.2_0 (active)
  py310-mako @1.2.4_0 (active)
  py310-markdown @3.4.1_0 (active)
  py310-markupsafe @2.1.1_0 (active)
  py310-setuptools @67.2.0_0 (active)
  python3_select @0.0_3 (active)
  python310 @3.10.10_0+lto+optimizations (active)
  python_select @0.3_10 (active)
  rav1e @0.6.3_0 (active)
  readline @8.1.2.000_0 (active)
  shared-mime-info @2.2_0 (active)
  sqlite3 @3.40.1_0 (active)
  tiff @4.5.0_0 (active)
  urw-fonts @1.0.7pre44_0 (active)
  webp @1.3.0_0 (active)
  x265 @3.4_2 (active)
  Xft2 @2.3.7_0 (active)
  xorg-libice @1.1.1_0 (active)
  xorg-libpthread-stubs @0.4_0 (active)
  xorg-libsm @1.2.4_0 (active)
  xorg-libX11 @1.8.3_1 (active)
  xorg-libXau @1.0.11_0 (active)
  xorg-libXaw @1.0.14_0 (active)
  xorg-libxcb @1.15_0+python311 (active)
  xorg-libXdmcp @1.1.4_0 (active)
  xorg-libXext @1.3.5_0 (active)
  xorg-libXmu @1.1.4_0 (active)
  xorg-libXt @1.2.1_0 (active)
  xorg-xcb-proto @1.15.2_0+python311 (active)
  xorg-xcb-util @0.4.1_0 (active)
  xorg-xorgproto @2022.2_0 (active)
  xpm @3.5.14_0 (active)
  xrender @0.9.11_0 (active)
  xz @5.2.10_0 (active)
  zlib @1.2.13_0 (active)
  zstd @1.5.4_0 (active)

**Comment by jschappel** [comment]
@oliwial23 Hmmmm... The good news is that graphviz is on your path. When you installed graphviz did you install it using `homebrew` and `macports`?

Also your you mind opening `drracket` and running the following in the REPL and let me know what the output is? 
```racket
(system "dot -v")
```
```racket
(system "/usr/local/bin/dot -v")
```
Incase you have never seen the [system](https://docs.racket-lang.org/reference/subprocess.html#%28def._%28%28lib._racket%2Fsystem..rkt%29._system%29%29) function before, it just executes the given command in your shell line and outputs the response in racket.

**Comment by oliwial23** [comment]
I installed it using macports first, then using homebrew when it wouldn't run. 
Attached is the output to (system "dot -v") and (system "/usr/local/bin/dot -v"):
<img width="1440" alt="Bildschirm­foto 2023-02-15 um 19 23 11" src="https://user-images.githubusercontent.com/119520637/219226273-6ebd7544-a13e-4aae-a5b8-def3ecb50bdd.png">

**Comment by jschappel** [comment]
Ahhhh ok I see the issue now. It seems that racket is not sourcing your `.bashrc` or `.bash_profile`. This is why `(system "dot -v")` failed, but `(system "/usr/local/bin/dot -v")` worked (the second one uses the absolute path to the `dot` executable). Is this something you want to try and fix? If so I an point to to the function that needs to be fixed. If not I can go ahead and fix it 😄

**Comment by oliwial23** [comment]
I would love to try fixing things on my own in the future. But frankly, yesterday was the first time I have heard of fem or started working with my Mac's terminal. So, I would appreciate the help. If you don't mind maybe you could explain to me how you solve it?

**Comment by jschappel** [comment]
Of course! We are always looking for new contributors so once you feel comfortable check out the issues tab and feel free to @ me with questions... I guess the best way to explain the fix is to give you brief overview of how a computers file system works. 

----

### What is a filepath?
The most important concept to understand is what a file path is. A file path is a string of characters used to uniquely identify a location in a directory (also called a folder). There are two types of file paths that we as computer programmers deal with on a daily basis:
1. `absolute path`: An absolute path is the full path to a file or directory. It is relative to the root directory of your system. 
    - An absolute path ALWAYS starts with `/`. 
    - For example: we have a file named `marco.cpp` located in the folder named `SHU` then the absolute path to marco.cpp would be `/SHU/marco.cpp`
      - In the above the first `/` says we are starting at the root directory
      - `SHU/` says we are looking in the folder SHU 
      - marco.cpp is the file we are pointing to
1. `relative path` : The relative path is relative to your present working directory
    - A relative path ALWAYS starts with `./`
      -  For example: Lets say instead of starting in the root directory we are starting in the folder `SHU`. Then the relative path to marco.cpp is `./marco.cpp`

### What is the PATH variable? 
Now there is one more concept we need to understand which is what a systems `PATH` variable is (not to be confused with a file path 😖).  PATH can be thought of as a list containing a set of directories where executable programs are located. If you want to see every thing on your PATH you can run `echo $PATH` in your terminal.
- `echo` means display (similar to [displayln](https://docs.racket-lang.org/reference/Writing.html#%28def._%28%28lib._racket%2Fprivate%2Fmisc..rkt%29._displayln%29%29) in racket)
- In order to reference a variable in shell you start with a `$`. (Yes your terminal uses a programming language called shell)
- So when we put it together we are saying, "print the variable PATH"

The important thing about the PATH variable is that it allows you to call executable programs using a "shorthand notation". A great example of this is the command `ls`. if you run `ls` in your terminal it will print all files and directories within the current directory that you are in. The full path to the ls program on my machine is `/bin/ls` this means that if you type `/bin/ls` in your terminal it will do the same thing as running `ls`. This is because ls is in your PATH so you can use the "shorthand" ls notation (`ls`) instead of `/bin/ls`


----
### Whats the fix? 
With that out of the way lets look at the output that you sent me from running `whereis dot`
```shell
$ wheris bash
dot: /usr/local/bin/dot /usr/local/share/man/man1/dot.1
```
Lets only focus on `/usr/local/bin/dot`. Its a relative path 🎉!!! What its saying is from the root directory there is a folder called `usr` and in that folder there is a folder called `local` and in that folder there is a folder called `bin` and in that folder there is a file called `dot` (are you noticing that directories use a recursive structure! YAY recursion ❤️). It turns out the dot file is the graphviz program that we want to run!!

Now there seems to be a issue where invoking the [system](https://docs.racket-lang.org/reference/subprocess.html#%28def._%28%28lib._racket%2Fsystem..rkt%29._system%29%29) function is not properly setting up your path meaning we can not use the shorthand notation (`dot`) and we instead need to use ` /usr/local/bin/dot`. So the fix is to instead use the absolute path 🎉 🚀 . The solution can be found here: #62 


Let me know if you have any questions and I'm sure @morazanm or @jasonhemann would be happy to explain the above in more detail with you in class
