### ISSUE TITLE
(add-node ...) and (add-edge ...) remove dashes from symbols 

### ISSUE THREAD

**Issue by oliwial23** [morazanm/fsm#73]
## Describe the bug
When using (add-node ...) or (add-edge ...) from lib.rkt, and a given symbol (like a node) contains a dash, that dash is removed. 

## Steps to Reproduce
1) Use #lang fsm and (require "lib.rkt")
2) Run

```
 (add-node (create-graph 'cgraph #:atb (hash 'rankdir "LR"))
          'sample-node-using-dashes)
```
3) Or run

```
(add-edge (create-graph 'cgraph #:atb (hash 'rankdir "LR"))
          "a" 'sample-node-using-dashes 'S)
```

4) See error

## Expected Behavior
The node's name is supposed to remain with dashes. 
In this case: 'sample-node-using-dashes
Instead, it turns to: 'samplenodeusingdashes

## OS Observed On
The operating system the bug was found on:
macOS Ventura 13.1

## Screenshots

<img width="1249" alt="Bildschirm­foto 2023-06-06 um 23 47 59" src="https://github.com/morazanm/fsm/assets/119520637/e431f6f2-76b4-44d0-af22-b0d136da3312">

<img width="1249" alt="Bildschirm­foto 2023-06-06 um 23 49 56" src="https://github.com/morazanm/fsm/assets/119520637/c252a742-f764-49ba-b55b-87e1933d9243">

**Comment by jschappel** [comment]
Hey @oliwial23  :wave:. This is not a bug. The reason this happens is because the dot language does not allow dashes in the name of a node or edge. You will notice that both `add-edge` and `add-node` set the label attribute to contain the dashes name so when you generate the png it will still have the dash in the name. See the below example: 


```racket
#lang racket
(require "lib.rkt")

(define init-graph (create-graph 'cgraph #:atb (hash 'rankdir "LR")))

(define nodes '(A-1 A-2))

(graph->bitmap
 (add-edge (foldr (lambda (name graph) (add-node graph name)) init-graph nodes)
           'a-name
           'A-1
           'A-2)
 (current-directory)
 "test")

(delete-file "test.dot")
(delete-file "test.png")
```

The dotfile produced (notice the labels)
```
digraph cgraph {
    rankdir="LR";
    A1 [color="black", shape="circle", label="A-1"];
    A2 [color="black", shape="circle", label="A-2"];
    A1 -> A2 [fontsize=15, label="a-name"];
}
```

The image produced
![test](https://github.com/morazanm/fsm/assets/18121440/0a0df4c3-bf7a-435d-8b25-7a398e605bc6)


Let me know if this is not what you are looking for

-Josh

**Comment by jschappel** [comment]
@oliwial23 I added some [documention](https://morazanm.github.io/fsm/dev/index.html) around the library.
